<?xml version="1.0" encoding="utf-8"?><Database Name="Hangouts" Class="HangoutsDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=108.58.151.10,1433;Initial Catalog=Hangouts;Persist Security Info=True;User ID=ankur" SettingsObjectName="Hangouts.DataAccess.Properties.Settings" SettingsPropertyName="HangoutsConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.RetrieveAvailableWines" Method="RetrieveAvailableWines">
    <Parameter Name="PlantFinal" Parameter="plantFinal" Type="System.Int32" DbType="Int" />
    <Parameter Name="CardID" Parameter="cardID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveAvailableWinesResult">
      <Column Name="SKU" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Vintage" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="RegPrice" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="AverageRating" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Liked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SmallImageUrl" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RetrieveWineReviews" Method="RetrieveWineReviews">
    <Parameter Name="WineID" Parameter="wineID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CardID" Parameter="cardID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveWineReviewsResult">
      <Column Name="SKUId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SKU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="[Sub-Region]" Member="Sub_Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GrapeVerietal" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="RegPrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="AverageRating" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="UsersRating" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BottleSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LargeImageURL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Liked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Information" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoreInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rating" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TastingNotes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReviewComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>