<?xml version="1.0" encoding="utf-8"?><Database Name="Hangouts" Class="HangoutsDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=108.58.151.10,1433;Initial Catalog=Hangouts;Persist Security Info=True;User ID=ankur" SettingsObjectName="Hangouts.DataAccess.Properties.Settings" SettingsPropertyName="HangoutsConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.RetrieveRatingsByUserId" Method="RetrieveRatingsByUserId">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveRatingsByUserIdResult">
      <Column Name="RatingStars" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RatingText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SKU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RetrieveWineDetails" Method="RetrieveWineDetails">
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveWineDetailsResult">
      <Column Name="SKU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="[Sub-Region]" Member="Sub_Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GrapeVerietal" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="RegPrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="AverageRating" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="UsersRating" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BottleSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LargeImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Liked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RetrieveAvailableWines" Method="RetrieveAvailableWines">
    <Parameter Name="PlantFinal" Parameter="plantFinal" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveAvailableWinesResult">
      <Column Name="SKU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Vintage" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="RegPrice" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="AverageRating" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="Liked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SmallImageURL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUpdateLike" Method="InsertUpdateLike">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int32" DbType="Int" />
    <Parameter Name="Liked" Parameter="liked" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AuthenticateUser" Method="AuthenticateUser">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="AuthenticateUserResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RetrieveRatingsBySKU" Method="RetrieveRatingsBySKU">
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int32" DbType="Int" />
    <ElementType Name="RetrieveRatingsBySKUResult">
      <Column Name="RatingStars" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RatingText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SKU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUpdateReview" Method="InsertUpdateReview">
    <Parameter Name="ReviewID" Parameter="reviewID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PlantFinal" Parameter="plantFinal" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ReviewDate" Parameter="reviewDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CardID" Parameter="cardID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cost" Parameter="cost" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="RatingStars" Parameter="ratingStars" Type="System.Int32" DbType="Int" />
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int32" DbType="Int" />
    <Parameter Name="CommentsTitle" Parameter="commentsTitle" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="RatingText" Parameter="ratingText" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="ReviewUserId" Parameter="reviewUserId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteReview" Method="DeleteReview">
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReviewUserId" Parameter="reviewUserId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>